Update tfonnx.py
Quick fix for:
AttributeError: np.cast was removed in the NumPy 2.0 release. Use np.asarray(arr, dtype=dtype) instead.

Signed-off-by: LoreBadTime <concas324@gmail.com>